workflows:
  android-workflow:
    name: Build Android APK
    environment:
      groups:
        - keystore  # Este grupo debe incluir las variables:
                    # CM_KEYSTORE, CM_KEYSTORE_PASSWORD, CM_KEY_ALIAS, CM_KEY_PASSWORD
      vars:
        FLET_VERSION: "0.28.3"
        FLUTTER_VERSION: "3.22.0"
    scripts:
      - name: Setup Flutter
        script: |
          flutter channel stable
          flutter upgrade
          flutter --version
      - name: Install dependencies
        script: |
          sudo apt-get update
          sudo apt-get install -y python3-pip openjdk-17-jdk
          python3 -m pip install --upgrade pip
          python3 -m pip install flet==$FLET_VERSION
      - name: Prepare keystore for signing
        script: |
          mkdir -p ~/.keystore
          # Copia el keystore desde la ruta proporcionada por Codemagic
          # y lo renombra a 'release.jks' para que flet lo encuentre.
          cp "$CM_KEYSTORE_PATH" ~/.keystore/release.jks
      - name: Build APK
        script: |
          flet clean
          flet pack main.py --name MiAppFlet
          flet build apk --build-version 1.0.0 --keystore ~/.keystore/release.jks \
            --keystore-password $CM_KEYSTORE_PASSWORD \
            --keystore-key-alias $CM_KEY_ALIAS \
            --key-password $CM_KEY_PASSWORD
    artifacts:
      - build/app/outputs/flutter-apk/*.apk
      - build/apk/*.apk
    publishing:
      scripts:
        - name: Listar archivos generados
          script: ls -R build/
