workflows:
  android-workflow:
    name: Build Android APK
    environment:
      groups:
        - keystore
      vars:
        FLET_VERSION: "0.28.3"
        FLUTTER_VERSION: "3.22.0"
    scripts:
      - name: Setup Flutter
        script: |
          flutter channel stable
          flutter upgrade
          flutter --version
      - name: Install dependencies
        script: |
          sudo apt-get update
          sudo apt-get install -y python3-pip openjdk-17-jdk
          python3 -m pip install --upgrade pip
          python3 -m pip install flet==$FLET_VERSION
          python3 -m pip install docxtpl pandas
      - name: Inject Android permissions
        script: |
          MANIFEST_PATH=android/app/src/main/AndroidManifest.xml
          if grep -q "WRITE_EXTERNAL_STORAGE" "$MANIFEST_PATH"; then
            echo "Permisos ya presentes"
          else
            sed -i '/<manifest/a \
            <uses-permission android:name="android.permission.READ_EXTERNAL_STORAGE"/>\n\
            <uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE"/>' "$MANIFEST_PATH"

            sed -i '/<application/a \
            android:requestLegacyExternalStorage="true"' "$MANIFEST_PATH"
          fi

      - name: Build APK
        script: |
          flet clean
          flet pack main.py --name MiAppFlet
          flet build apk --build-version 1.0.0 
    artifacts:
      - build/app/outputs/flutter-apk/*.apk
      - build/apk/*.apk
    publishing:
      scripts:
        - name: Listar archivos generados
          script: ls -R build/
